image: registry.gitlab.com/csicar/pskt

build:
   stage: build
   script:
      - make
      - make install
      - pwd
      - ls /root/.local/bin
      - cp /root/.local/bin/purs .
   artifacts:
      paths:
      - purs

test:
   stage: test
   script:
      - purs
      - make test