image: registry.gitlab.com/csicar/pskt

build:
        stage: build
        script:
                - make
                - make install
                - pwd
                - ls /root/.local/bin
                - ls /builds/csicar/pskt/.stack-work/install/x86_64-linux/lts-13.12/8.6.4/bin/
        artifacts:
                paths:
                - /root/.local/bin/
                - /builds/csicar/pskt/.stack-work/install/x86_64-linux/lts-13.12/8.6.4/bin/
test:
        stage: test
        script:
                - make test
        