image: csicar/pskt

build:
        stage: build
        script:
                - make
                - make install
        artifacts:
                paths:
                - /root/.local/bin/
test:
        stage: test
        script:
                - make test
        