image: registry.gitlab.com/csicar/pskt

build:
   stage: build
   script:
      - make
      - make install
      - pwd
      - ls /root/.local/bin
   artifacts:
      paths:
      - /root/.local/

test:
   stage: test
   script:
      - purs
      - make test