image: registry.gitlab.com/csicar/pskt

build:
   stage: build
   script:
      - make
      - make install
      - cp /root/.local/bin/pskt .
   artifacts:
      paths:
      - pskt

test:
   stage: test
   script:
      - stack test